<?php get_header(); the_post(); ?>


<div class="[ container ]">
	<section>
		<h2>Datos y código abierto</h2>
		<p>La plataforma Constitución CDMX – Espacio de Encuentro fue desarrollada por un equipo multidisciplinario de servidores públicos, diseñadores, desarrolladores y académicos. Este proyecto encuentra su fundamento en el <a href="http://www.consejeria.df.gob.mx/portal_old/uploads/gacetas/6cab5c7ee610f015659049c6fbb777a9.pdf" target="_blank">Acuerdo</a> publicado en la Gaceta Oficial de la Ciudad de México el 5 de febrero de 2016, mediante la cual se integra el Grupo de Trabajo que Apoya al Jefe de Gobierno en la Elaboración del Proyecto de Constitución Política de la Ciudad de México.</p>
		<p>En la concepción y desarrollo del proyecto estuvieron involucradas la Consejería Jurídica y de Servicios Legales y la Dirección General de Creatividad de la Agencia de Gestión Urbana, también conocido como <a href="http://labcd.mx/" target="_blank">Laboratorio para la Ciudad</a>, área experimental del Gobierno de la Ciudad de México. </p>
		<p>La plataforma <a href="http://pubpub.org/" target="_blank">PubPub</a>, fue desarrollada originalmente por estudiantes de posgrado del <a href="http://www.media.mit.edu/" target="_blank">MIT Media Lab</a>, y adaptada para los fines de este proyecto en conjunto con desarrolladores del Laboratorio para la Ciudad. Su <a href="http://constitucioncdmx.pubpub.org/" target="_blank">implementación en Constitución CDMX</a> no representó ninguna erogación directa para el Gobierno de la Ciudad de México, y se hizo en el marco de una <a href="http://debatecd.mx/" target="_blank">colaboración preexistente</a> con el MIT Media Lab, cuyos fines son la investigación y generación de conocimiento público.</p>
		<p>Para la programación y desarrollo del sitio web, se recurrió a <a href="http://www.pcuervo.com/" target="_blank">Pequeño Cuervo</a>, agencia digital con presencia internacional, integrada por emprendedores mexicanos, con base en la Ciudad de México. Para su contratación, se optó por una adjudicación directa dentro de la partida presupuestal de consultorías informáticas de la Consejería Jurídica, y representó una erogación de $135,000 pesos.</p>
		<p>La propiedad intelectual de la plataforma es de la Consejería Jurídica. Sin embargo, el código fuente de la página estará abierto y disponible para su libre uso en un repositorio de GitHub, una vez terminada la etapa de participación ciudadana en el proyecto de la Constitución. Por otro lado, todos los contenidos puestos en línea en la plataforma PubPub, se publican con una licencia <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">Creative Commons 4.0</a>; los resultados del sondeo Imagina tu Ciudad estarán disponibles en formatos abiertos para el uso y análisis de la ciudadanía una vez concluido el ejercicio de participación ciudadana.</p>
		<p>Las imágenes del video de la página de inicio fueron utilizadas con la autorización de su realizador, Santiago Arau Pontones, y son un extracto de su obra <a href="https://vimeo.com/139416145" target="_blank">La Ciudad</a>.</p>
	</section>
</div>

<?php get_footer(); ?>